#!/bin/bash

if dpkg-query -W -f='${Status}' nginx | grep -c 'ok installed'
then
	if dpkg-query -W -f='${Status}' php7.0 | grep -c 'ok installed'
	then
        	if dpkg-query -W -f='${Status}' mysql-server | grep -c 'ok installed'
		then
			if dpkg-query -W -f='${Status}' phpmyadmin | grep -c 'ok installed'
	                then
				if dpkg-query -W -f='${Status}' wordpress 
				ls /var/www/html/| grep -c 'wordpress'
				then
					echo "Kõik on juba installeeritud."
				else
					sudo apt install -y apache2 php7.0 php7.0-mysql libapache2-mod-php7.0 php7.0-cli php7.0-cgi php7.0-gd phpmyadmin php-mbstring php-xml php-php-gettext php-gettext mysql-client mysql-server
					sudo mysql_secure_installation
					wget -c http://wordpress.org/latest.tar.gz
					tar -xzvf latest.tar.gz
					rm -rf ./latest.tar.gz
					#USERNAME & PASSWORD
					clear
					echo -n "Sisestage tahetud Wordpressi ja MYSql'i kasutajanimi: "
					read kasutaja
					clear
					echo "Sisestage tahetud Wordpressi ja MYSql'i parool: "
					read parool
					#WORDPRESS PERMISSIONS & DEFAULT SETTINGS
					sudo rsync -av wordpress/* /var/www/html/wordpress
					sudo chown -R www-data:www-data /var/www/html/
					sudo chmod -R 755 /var/www/html/
					wget https://raw.githubusercontent.com/kleanuria/rsha/master/praks4/default -P /etc/nginx/sites-available/
					systemctl reload nginx.service
					#DATABASE CREATE
					echo "CREATE DATABASE wp_page;" | mysql -uroot -p$parool
					echo "GRANT ALL PRIVILEGES ON wp_page.* TO '$kasutaja@localhost' IDENTIFIED BY '$parool';" | mysql -uroot -p$parool
					echo "FLUSH PRIVILEGES;" | mysql -uroot -p$parool
				fi
                	else
				sudo apt install -y phpmyadmin php-mbstring php-xml php-php-gettext php-gettext
				ln -s /usr/share/phpmyadmin/ /var/www/html/phpmyadmin
               		fi
		else
		sudo apt install -y mysql-server mysql-client
		fi
	else
	sudo apt install -y php7.0 php7.0-mysql libapache2-mod-php7.0 php7.0-cli php7.0-cgi php7.0-gd php-mbstring php-xml php-php-gettext php-gettext
	fi
else
sudo apt install -y nginx
fi
